cat_folder = "Cat"
dog_folder = "Dog"
cutoff = 0.8
image_crop = 50
encoder = {"cat": 0, "dog": 1}
train_data = 'TrainData.npy'
test_data = 'TestData.npy'
batch_size = 64

input_size = 2500
dense1 = 1024
dense2 = 512
dense3 = 512
output = 1
keep_prob = 0.3
learning_rate = 0.0001
num_epochs = 10
verbose = 100
current_dir = "E:\My Projects\Cat-vs-Dog-Image-Classifier-Differnet-Models-with-Pytroch\Data"